module.exports = {
  products: [
    {
      _id: '111111111111111111111111',
      name: 'Hiskywin Full Zip Running Shirts Thermal Workout',
      category: 'Shirts',
      image: './Static/Assets/images/1.jpg',
      price: 59,
      brand: 'Hiskywin',
      description:'An easy to wear straight-leg jean with classic styling, this versatile dark indigo pair is made from a modern fabrication with added stretch that looks like sophisticated, timeless denim but feels effortless and holds its shape wear after wear.',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '222222222222222222222222',
      name: 'Nike Full-Zip Hoodie Mens Workout Sweatshirt',
      category: 'Shirts',
      image: './Static/Assets/images/2.jpg',
      price: 70,
      brand: 'Nike',
      description:'An easy to wear straight-leg jean with classic styling, this versatile dark indigo pair is made from a modern fabrication with added stretch that looks like sophisticated, timeless denim but feels effortless and holds its shape wear after wear.',
      rating: 5,
      numReviews: 51,
      countInStock: 16,
    },
    {
      _id: '3',
      name: 'Adidas Mens Long Sleeve Hoodie',
      category: 'Shirts',
      image: './Static/Assets/images/3.jpg',
      price: 59,
      brand: 'Adidas',
      description:'An easy to wear straight-leg jean with classic styling, this versatile dark indigo pair is made from a modern fabrication with added stretch that looks like sophisticated, timeless denim but feels effortless and holds its shape wear after wear.',
      rating: 4,
      numReviews: 45,
      countInStock: 23,
    },
    {
      _id: '4',
      name: 'Under Armour Mens Sportstyle Tricot Joggers',
      category: 'Pants',
      image: './Static/Assets/images/4.jpg',
      price: 90,
      brand: 'Under Armour',
      description:'An easy to wear straight-leg jean with classic styling, this versatile dark indigo pair is made from a modern fabrication with added stretch that looks like sophisticated, timeless denim but feels effortless and holds its shape wear after wear.',
      rating: 2.5,
      numReviews: 198,
      countInStock: 3,
    },
    {
      _id: '5',
      name: 'Champion Mens Graphic Powerblend Fleece Jogger',
      category: 'Pants',
      image: './Static/Assets/images/5.jpg',
      price: 119,
      brand: 'Champion',
      description:'An easy to wear straight-leg jean with classic styling, this versatile dark indigo pair is made from a modern fabrication with added stretch that looks like sophisticated, timeless denim but feels effortless and holds its shape wear after wear.',
      rating: 3.5,
      numReviews: 89,
      countInStock: 9,
    },
    {
      _id: '6',
      name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
      category: 'Pants',
      image: './Static/Assets/images/6.jpg',
      price: 85,
      brand: 'Aelfric Eden',
      description:'An easy to wear straight-leg jean with classic styling, this versatile dark indigo pair is made from a modern fabrication with added stretch that looks like sophisticated, timeless denim but feels effortless and holds its shape wear after wear.',
      rating: 4.5,
      numReviews: 45,
      countInStock: 2,
    },
    {
      _id: '7',
      name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
      category: 'Pants',
      image: './Static/Assets/images/7.jpg',
      price: 85,
      brand: 'Aelfric Eden',
      description:'An easy to wear straight-leg jean with classic styling, this versatile dark indigo pair is made from a modern fabrication with added stretch that looks like sophisticated, timeless denim but feels effortless and holds its shape wear after wear.',
      rating: 4.5,
      numReviews: 45,
      countInStock: 5,
    },
    {
      _id: '8',
      name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
      category: 'Pants',
      image: './Static/Assets/images/8.jpg',
      price: 85,
      brand: 'Aelfric Eden',
      description:'An easy to wear straight-leg jean with classic styling, this versatile dark indigo pair is made from a modern fabrication with added stretch that looks like sophisticated, timeless denim but feels effortless and holds its shape wear after wear.',
      rating: 4.5,
      numReviews: 45,
      countInStock: 12,
    },
  ]
};

